n = int(input('Digite um número inteiro: '))
#print('A tabuada de {} é\n{}x1={}\n{}x2={}\n{}x3={}\n{}x4={}\n{}x5={}\n'
      #.format(n,n,(n*1),n,(n*2),n,(n*3),n,(n*4),n,(n*5)))
print('-'*11)
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 4, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x {:1} = {}'.format(n, 10, n*10))
print('-'*11)